homeController:
  dev-name: mauricio
  app-name: dinossauro em dev
  msg: "frango frito"
spring:
  profiles: development
---
homeController:
  msg: "frango frito em produção"
spring:
  profiles: production
  thymeleaf:
    cache: false