import org.junit.Test;
import org.openqa.selenium.Capabilities;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeDriverService;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.CommandExecutor;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.service.DriverService;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mbsilva' at '11/23/16 7:21 PM' with Gradle 2.12
 *
 * @author mbsilva, @date 11/23/16 7:21 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        System.setProperty("webdriver.chrome.driver","/Users/mbsilva/Development/gapinc/selenium-timezones/chromedriver");
        Map envMap = new HashMap<>();
        envMap.put("TZ", "Japan");
        ChromeDriverService service = new ChromeDriverService.Builder().usingAnyFreePort().withEnvironment(envMap).build();
        
        WebDriver driver = new ChromeDriver(service);
        driver.get("http://localhost:3000/static");
    }
}
