/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mbsilva' at '11/23/16 7:21 PM' with Gradle 2.12
 *
 * @author mbsilva, @date 11/23/16 7:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
